package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.po.TbAdminUser;
import java.util.List;

public interface TbAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbggenerated
     */
    int insert(TbAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbggenerated
     */
    TbAdminUser selectByPrimaryKey(Integer taUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbggenerated
     */
    List<TbAdminUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbAdminUser record);
}