package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.po.TbStuTea;
import java.util.List;

public interface TbStuTeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    int insert(TbStuTea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    TbStuTea selectByPrimaryKey(Integer stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    List<TbStuTea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbStuTea record);
}