package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.po.TbStudent;
import com.teach.manager.teachmanager.pojo.vo.StudentVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int insert(TbStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    TbStudent selectByPrimaryKey(Integer tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    List<TbStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbStudent record);

    /**
     * @Description: 条件查询学生信息
     * @Param1: pageCount
     * @Param2: pageSize
     * @Param3: query
     * @Param4: sort
     * @Param5: order
     * @return: java.util.List<com.teach.manager.teachmanager.pojo.po.TbStudent>
     * @Author: malin
     * @Date: 2019-04-17
     */
    List<TbStudent> findAllByPage(@Param(value = "pageCount") Integer pageCount, @Param(value = "pageSize") Integer pageSize,
                                  @Param(value = "studentVo") StudentVo studentVo, @Param(value = "sort") String sort,
                                  @Param(value = "order") String order);

    /**
     * @Description: 获取学生数据的总数
     * @Param1:
     * @return: int
     * @Author: malin
     * @Date: 2019-04-17
     */
    int findStudentCount(@Param(value = "studentVo") StudentVo studentVo);
}