package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.dos.TbStudent;
import java.util.List;

public interface TbStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int insert(TbStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    TbStudent selectByPrimaryKey(Integer tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    List<TbStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbStudent record);
}