package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.dos.TbTeacher;
import java.util.List;

public interface TbTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    int insert(TbTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    TbTeacher selectByPrimaryKey(Integer ttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    List<TbTeacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbTeacher record);
}