package com.teach.manager.teachmanager.dao;

import com.teach.manager.teachmanager.pojo.po.TbUserRole;
import java.util.List;

public interface TbUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbggenerated
     */
    int insert(TbUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbggenerated
     */
    List<TbUserRole> selectAll();
}