package com.teach.manager.teachmanager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class TbPaper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_id
     *
     * @mbggenerated
     */
    private Integer tpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_type_id
     *
     * @mbggenerated
     */
    private Integer tpTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_num_id
     *
     * @mbggenerated
     */
    private Integer tpNumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_info
     *
     * @mbggenerated
     */
    private String tpInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_weight
     *
     * @mbggenerated
     */
    private Integer tpWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_del
     *
     * @mbggenerated
     */
    private String tpDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_created_date
     *
     * @mbggenerated
     */
    private Date tpCreatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paper.tp_updated_date
     *
     * @mbggenerated
     */
    private Date tpUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_paper
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_id
     *
     * @return the value of tb_paper.tp_id
     *
     * @mbggenerated
     */
    public Integer getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_id
     *
     * @param tpId the value for tb_paper.tp_id
     *
     * @mbggenerated
     */
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_type_id
     *
     * @return the value of tb_paper.tp_type_id
     *
     * @mbggenerated
     */
    public Integer getTpTypeId() {
        return tpTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_type_id
     *
     * @param tpTypeId the value for tb_paper.tp_type_id
     *
     * @mbggenerated
     */
    public void setTpTypeId(Integer tpTypeId) {
        this.tpTypeId = tpTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_num_id
     *
     * @return the value of tb_paper.tp_num_id
     *
     * @mbggenerated
     */
    public Integer getTpNumId() {
        return tpNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_num_id
     *
     * @param tpNumId the value for tb_paper.tp_num_id
     *
     * @mbggenerated
     */
    public void setTpNumId(Integer tpNumId) {
        this.tpNumId = tpNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_info
     *
     * @return the value of tb_paper.tp_info
     *
     * @mbggenerated
     */
    public String getTpInfo() {
        return tpInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_info
     *
     * @param tpInfo the value for tb_paper.tp_info
     *
     * @mbggenerated
     */
    public void setTpInfo(String tpInfo) {
        this.tpInfo = tpInfo == null ? null : tpInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_weight
     *
     * @return the value of tb_paper.tp_weight
     *
     * @mbggenerated
     */
    public Integer getTpWeight() {
        return tpWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_weight
     *
     * @param tpWeight the value for tb_paper.tp_weight
     *
     * @mbggenerated
     */
    public void setTpWeight(Integer tpWeight) {
        this.tpWeight = tpWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_del
     *
     * @return the value of tb_paper.tp_del
     *
     * @mbggenerated
     */
    public String getTpDel() {
        return tpDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_del
     *
     * @param tpDel the value for tb_paper.tp_del
     *
     * @mbggenerated
     */
    public void setTpDel(String tpDel) {
        this.tpDel = tpDel == null ? null : tpDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_created_date
     *
     * @return the value of tb_paper.tp_created_date
     *
     * @mbggenerated
     */
    public Date getTpCreatedDate() {
        return tpCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_created_date
     *
     * @param tpCreatedDate the value for tb_paper.tp_created_date
     *
     * @mbggenerated
     */
    public void setTpCreatedDate(Date tpCreatedDate) {
        this.tpCreatedDate = tpCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paper.tp_updated_date
     *
     * @return the value of tb_paper.tp_updated_date
     *
     * @mbggenerated
     */
    public Date getTpUpdatedDate() {
        return tpUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paper.tp_updated_date
     *
     * @param tpUpdatedDate the value for tb_paper.tp_updated_date
     *
     * @mbggenerated
     */
    public void setTpUpdatedDate(Date tpUpdatedDate) {
        this.tpUpdatedDate = tpUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tpId=").append(tpId);
        sb.append(", tpTypeId=").append(tpTypeId);
        sb.append(", tpNumId=").append(tpNumId);
        sb.append(", tpInfo=").append(tpInfo);
        sb.append(", tpWeight=").append(tpWeight);
        sb.append(", tpDel=").append(tpDel);
        sb.append(", tpCreatedDate=").append(tpCreatedDate);
        sb.append(", tpUpdatedDate=").append(tpUpdatedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}