package com.teach.manager.teachmanager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class TbRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.tr_role_id
     *
     * @mbggenerated
     */
    private Integer trRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.tr_name
     *
     * @mbggenerated
     */
    private String trName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.tr_created_date
     *
     * @mbggenerated
     */
    private Date trCreatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.tr_updated_date
     *
     * @mbggenerated
     */
    private Date trUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.tr_role_id
     *
     * @return the value of tb_role.tr_role_id
     *
     * @mbggenerated
     */
    public Integer getTrRoleId() {
        return trRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.tr_role_id
     *
     * @param trRoleId the value for tb_role.tr_role_id
     *
     * @mbggenerated
     */
    public void setTrRoleId(Integer trRoleId) {
        this.trRoleId = trRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.tr_name
     *
     * @return the value of tb_role.tr_name
     *
     * @mbggenerated
     */
    public String getTrName() {
        return trName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.tr_name
     *
     * @param trName the value for tb_role.tr_name
     *
     * @mbggenerated
     */
    public void setTrName(String trName) {
        this.trName = trName == null ? null : trName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.tr_created_date
     *
     * @return the value of tb_role.tr_created_date
     *
     * @mbggenerated
     */
    public Date getTrCreatedDate() {
        return trCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.tr_created_date
     *
     * @param trCreatedDate the value for tb_role.tr_created_date
     *
     * @mbggenerated
     */
    public void setTrCreatedDate(Date trCreatedDate) {
        this.trCreatedDate = trCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.tr_updated_date
     *
     * @return the value of tb_role.tr_updated_date
     *
     * @mbggenerated
     */
    public Date getTrUpdatedDate() {
        return trUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.tr_updated_date
     *
     * @param trUpdatedDate the value for tb_role.tr_updated_date
     *
     * @mbggenerated
     */
    public void setTrUpdatedDate(Date trUpdatedDate) {
        this.trUpdatedDate = trUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trRoleId=").append(trRoleId);
        sb.append(", trName=").append(trName);
        sb.append(", trCreatedDate=").append(trCreatedDate);
        sb.append(", trUpdatedDate=").append(trUpdatedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}