package com.teach.manager.teachmanager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class TbTeacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_id
     *
     * @mbggenerated
     */
    private Integer ttId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_name
     *
     * @mbggenerated
     */
    private String ttName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_subject_id
     *
     * @mbggenerated
     */
    private Integer ttSubjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_phone
     *
     * @mbggenerated
     */
    private String ttPhone;

    private Integer ttRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_del
     *
     * @mbggenerated
     */
    private String ttDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_created_date
     *
     * @mbggenerated
     */
    private Date ttCreatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tt_updated_date
     *
     * @mbggenerated
     */
    private Date ttUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_id
     *
     * @return the value of tb_teacher.tt_id
     * @mbggenerated
     */
    public Integer getTtId() {
        return ttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_id
     *
     * @param ttId the value for tb_teacher.tt_id
     * @mbggenerated
     */
    public void setTtId(Integer ttId) {
        this.ttId = ttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_name
     *
     * @return the value of tb_teacher.tt_name
     * @mbggenerated
     */
    public String getTtName() {
        return ttName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_name
     *
     * @param ttName the value for tb_teacher.tt_name
     * @mbggenerated
     */
    public void setTtName(String ttName) {
        this.ttName = ttName == null ? null : ttName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_subject_id
     *
     * @return the value of tb_teacher.tt_subject_id
     * @mbggenerated
     */
    public Integer getTtSubjectId() {
        return ttSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_subject_id
     *
     * @param ttSubjectId the value for tb_teacher.tt_subject_id
     * @mbggenerated
     */
    public void setTtSubjectId(Integer ttSubjectId) {
        this.ttSubjectId = ttSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_phone
     *
     * @return the value of tb_teacher.tt_phone
     * @mbggenerated
     */
    public String getTtPhone() {
        return ttPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_phone
     *
     * @param ttPhone the value for tb_teacher.tt_phone
     * @mbggenerated
     */
    public void setTtPhone(String ttPhone) {
        this.ttPhone = ttPhone == null ? null : ttPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_del
     *
     * @return the value of tb_teacher.tt_del
     * @mbggenerated
     */
    public String getTtDel() {
        return ttDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_del
     *
     * @param ttDel the value for tb_teacher.tt_del
     * @mbggenerated
     */
    public void setTtDel(String ttDel) {
        this.ttDel = ttDel == null ? null : ttDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_created_date
     *
     * @return the value of tb_teacher.tt_created_date
     * @mbggenerated
     */
    public Date getTtCreatedDate() {
        return ttCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_created_date
     *
     * @param ttCreatedDate the value for tb_teacher.tt_created_date
     * @mbggenerated
     */
    public void setTtCreatedDate(Date ttCreatedDate) {
        this.ttCreatedDate = ttCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tt_updated_date
     *
     * @return the value of tb_teacher.tt_updated_date
     * @mbggenerated
     */
    public Date getTtUpdatedDate() {
        return ttUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tt_updated_date
     *
     * @param ttUpdatedDate the value for tb_teacher.tt_updated_date
     * @mbggenerated
     */
    public void setTtUpdatedDate(Date ttUpdatedDate) {
        this.ttUpdatedDate = ttUpdatedDate;
    }

    public Integer getTtRole() {
        return ttRole;
    }

    public void setTtRole(Integer ttRole) {
        this.ttRole = ttRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ttId=").append(ttId);
        sb.append(", ttName=").append(ttName);
        sb.append(", ttSubjectId=").append(ttSubjectId);
        sb.append(", ttPhone=").append(ttPhone);
        sb.append(", ttDel=").append(ttDel);
        sb.append(", ttCreatedDate=").append(ttCreatedDate);
        sb.append(", ttUpdatedDate=").append(ttUpdatedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}