package com.teach.manager.teachmanager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class TbTeaSub implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tea_sub.tea_sub_id
     *
     * @mbggenerated
     */
    private Integer teaSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tea_sub.tea_subject_id
     *
     * @mbggenerated
     */
    private Integer teaSubjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tea_sub.tea_teacher_id
     *
     * @mbggenerated
     */
    private Integer teaTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tea_sub.tea_created_date
     *
     * @mbggenerated
     */
    private Date teaCreatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tea_sub.tea_updated_date
     *
     * @mbggenerated
     */
    private Date teaUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_tea_sub
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tea_sub.tea_sub_id
     *
     * @return the value of tb_tea_sub.tea_sub_id
     *
     * @mbggenerated
     */
    public Integer getTeaSubId() {
        return teaSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tea_sub.tea_sub_id
     *
     * @param teaSubId the value for tb_tea_sub.tea_sub_id
     *
     * @mbggenerated
     */
    public void setTeaSubId(Integer teaSubId) {
        this.teaSubId = teaSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tea_sub.tea_subject_id
     *
     * @return the value of tb_tea_sub.tea_subject_id
     *
     * @mbggenerated
     */
    public Integer getTeaSubjectId() {
        return teaSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tea_sub.tea_subject_id
     *
     * @param teaSubjectId the value for tb_tea_sub.tea_subject_id
     *
     * @mbggenerated
     */
    public void setTeaSubjectId(Integer teaSubjectId) {
        this.teaSubjectId = teaSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tea_sub.tea_teacher_id
     *
     * @return the value of tb_tea_sub.tea_teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeaTeacherId() {
        return teaTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tea_sub.tea_teacher_id
     *
     * @param teaTeacherId the value for tb_tea_sub.tea_teacher_id
     *
     * @mbggenerated
     */
    public void setTeaTeacherId(Integer teaTeacherId) {
        this.teaTeacherId = teaTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tea_sub.tea_created_date
     *
     * @return the value of tb_tea_sub.tea_created_date
     *
     * @mbggenerated
     */
    public Date getTeaCreatedDate() {
        return teaCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tea_sub.tea_created_date
     *
     * @param teaCreatedDate the value for tb_tea_sub.tea_created_date
     *
     * @mbggenerated
     */
    public void setTeaCreatedDate(Date teaCreatedDate) {
        this.teaCreatedDate = teaCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tea_sub.tea_updated_date
     *
     * @return the value of tb_tea_sub.tea_updated_date
     *
     * @mbggenerated
     */
    public Date getTeaUpdatedDate() {
        return teaUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tea_sub.tea_updated_date
     *
     * @param teaUpdatedDate the value for tb_tea_sub.tea_updated_date
     *
     * @mbggenerated
     */
    public void setTeaUpdatedDate(Date teaUpdatedDate) {
        this.teaUpdatedDate = teaUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tea_sub
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teaSubId=").append(teaSubId);
        sb.append(", teaSubjectId=").append(teaSubjectId);
        sb.append(", teaTeacherId=").append(teaTeacherId);
        sb.append(", teaCreatedDate=").append(teaCreatedDate);
        sb.append(", teaUpdatedDate=").append(teaUpdatedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}