package com.teach.manager.teachmanager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class TbUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.tar_user_id
     *
     * @mbggenerated
     */
    private Integer tarUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.tar_role_id
     *
     * @mbggenerated
     */
    private Integer tarRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.tar_created_date
     *
     * @mbggenerated
     */
    private Date tarCreatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.tar_updated_date
     *
     * @mbggenerated
     */
    private Date tarUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.tar_user_id
     *
     * @return the value of tb_user_role.tar_user_id
     *
     * @mbggenerated
     */
    public Integer getTarUserId() {
        return tarUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.tar_user_id
     *
     * @param tarUserId the value for tb_user_role.tar_user_id
     *
     * @mbggenerated
     */
    public void setTarUserId(Integer tarUserId) {
        this.tarUserId = tarUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.tar_role_id
     *
     * @return the value of tb_user_role.tar_role_id
     *
     * @mbggenerated
     */
    public Integer getTarRoleId() {
        return tarRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.tar_role_id
     *
     * @param tarRoleId the value for tb_user_role.tar_role_id
     *
     * @mbggenerated
     */
    public void setTarRoleId(Integer tarRoleId) {
        this.tarRoleId = tarRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.tar_created_date
     *
     * @return the value of tb_user_role.tar_created_date
     *
     * @mbggenerated
     */
    public Date getTarCreatedDate() {
        return tarCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.tar_created_date
     *
     * @param tarCreatedDate the value for tb_user_role.tar_created_date
     *
     * @mbggenerated
     */
    public void setTarCreatedDate(Date tarCreatedDate) {
        this.tarCreatedDate = tarCreatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.tar_updated_date
     *
     * @return the value of tb_user_role.tar_updated_date
     *
     * @mbggenerated
     */
    public Date getTarUpdatedDate() {
        return tarUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.tar_updated_date
     *
     * @param tarUpdatedDate the value for tb_user_role.tar_updated_date
     *
     * @mbggenerated
     */
    public void setTarUpdatedDate(Date tarUpdatedDate) {
        this.tarUpdatedDate = tarUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tarUserId=").append(tarUserId);
        sb.append(", tarRoleId=").append(tarRoleId);
        sb.append(", tarCreatedDate=").append(tarCreatedDate);
        sb.append(", tarUpdatedDate=").append(tarUpdatedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}