package com.teach.manager.teachmanager.pojo.dos;

import java.io.Serializable;

public class TbStuTea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stu_tea.st_id
     *
     * @mbggenerated
     */
    private Integer stId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stu_tea.st_teacher_id
     *
     * @mbggenerated
     */
    private Integer stTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stu_tea.st_student_id
     *
     * @mbggenerated
     */
    private Integer stStudentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stu_tea.st_id
     *
     * @return the value of tb_stu_tea.st_id
     *
     * @mbggenerated
     */
    public Integer getStId() {
        return stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stu_tea.st_id
     *
     * @param stId the value for tb_stu_tea.st_id
     *
     * @mbggenerated
     */
    public void setStId(Integer stId) {
        this.stId = stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stu_tea.st_teacher_id
     *
     * @return the value of tb_stu_tea.st_teacher_id
     *
     * @mbggenerated
     */
    public Integer getStTeacherId() {
        return stTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stu_tea.st_teacher_id
     *
     * @param stTeacherId the value for tb_stu_tea.st_teacher_id
     *
     * @mbggenerated
     */
    public void setStTeacherId(Integer stTeacherId) {
        this.stTeacherId = stTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stu_tea.st_student_id
     *
     * @return the value of tb_stu_tea.st_student_id
     *
     * @mbggenerated
     */
    public Integer getStStudentId() {
        return stStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stu_tea.st_student_id
     *
     * @param stStudentId the value for tb_stu_tea.st_student_id
     *
     * @mbggenerated
     */
    public void setStStudentId(Integer stStudentId) {
        this.stStudentId = stStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu_tea
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stId=").append(stId);
        sb.append(", stTeacherId=").append(stTeacherId);
        sb.append(", stStudentId=").append(stStudentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}